---
language: ruby
script: bundle exec middleman build

before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup > /dev/null'
script: rake build

after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish > /dev/null'

env:
  global:
    - GIT_COMMITTER_NAME=kubosho_
    - GIT_COMMITTER_EMAIL=ta2@o2p.jp
    - GIT_AUTHOR_NAME=kubosho_
    - GIT_AUTHOR_EMAIL=ta2@o2p.jp
    - secure: C1LfZkWyjzZJ7x0fowXKe9GJJt5sxNS0JpHOjeHKYbDjOf6xmWFIG8OEqrP4VE/9m1QhwvnNrzrxIwRmY06HzTIxA8Jz/oUxOCHfjN/6i26LnGlJpAos/Q0GuccEOx60H9jF6zzUHY7rcS8pWeNb7UlmPEUPLT2Nar35EhcyyzU=
