---
language: ruby
script: bundle exec middleman build

before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup > /dev/null'
script: rake build

after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish > /dev/null'

env:
  global:
    - GIT_COMMITTER_NAME=kubosho_
    - GIT_COMMITTER_EMAIL=ta2@o2p.jp
    - GIT_AUTHOR_NAME=kubosho_
    - GIT_AUTHOR_EMAIL=ta2@o2p.jp
    - secure: JEnAQD/oHEKE2/VFgH1KzS4CWuHhojc2Yl5jdvtMRR0Rehz9xVZR1VEiOKzIchZdqFWuEgZofeCdps9wVamG9WnMmFpmkqx35gR78iIouObZlAuFIrPqD58SnfzmQDmx1mmP83QUfpCV32k5LUsfLlrUmDPmGfNjmzrg7xSR51c=
