language: ruby
rvm:
  - 2.1.2

script: bundle exec middleman build

deploy:
  provider: heroku
  api_key:
    secure: X7hTnf1j0gW+Qe2i1yKXWTV1FXXgIx/XGdTk573+aYn8oRyw2BZeJcobsbN3Cw6a+0v5xFT0fabbWokTWPZZLeVdBI+M+yBxl1jW8AXF+IbBIeEM9qv9TdnaqZV9Nedq9JLa5FMbZnu4eKooRotzNuF6rXdkATxE8JKiFh/7tgo=
  app: o2p
  on:
    repo: o2project/blog.o2p.jp
    branch: develop
  run: "bundle exec middleman build"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b38467bb8c2231a9ec5b
    on_success: change
    on_failure: always
    on_start: false
