---
language: ruby

before_script:
  - '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$GH_TOKEN" ] && rake setup > /dev/null'

script:
  - rake build

after_success:
  - '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$GH_TOKEN" ] && rake publish > /dev/null'

env:
  global:
    - GIT_COMMITTER_NAME=kubosho_
    - GIT_COMMITTER_EMAIL=ta2@o2p.jp
    - GIT_AUTHOR_NAME=kubosho_
    - GIT_AUTHOR_EMAIL=ta2@o2p.jp
    - secure: V5V+JDryExRy5MxgBxBdJu1GCCfPgAjF5NTGB+DqmgyUZpSJzZE/+8LJ7fk2r4+2lFznf9P0EyEZV3lvgaCKQGx9hF4+l6hUUUHyTPa0/hW6hrcareqx3dmhTs8ff/LXos1LSFqkK0RZZ36ePCJCa1hRKEN0FpMtsPgY2yb6h7I=
