---
language: ruby
script: bundle exec middleman build

before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup > /dev/null'
script: rake build

after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish > /dev/null'

env:
  global:
    - GIT_COMMITTER_NAME=kubosho_
    - GIT_COMMITTER_EMAIL=ta2@o2p.jp
    - GIT_AUTHOR_NAME=kubosho_
    - GIT_AUTHOR_EMAIL=ta2@o2p.jp
    - secure: EB1/pDKbQdW0CbYtivp1xI3QvPJ/hvtcVKQQR3+4uQZiWzSX6jnhyylH6+twzZXX2zU0RGHdaWV4rI5o81eK5iqtlfFN0gk6wBIqvmVW13ZOxkGwyUHuk6bqL7b2cU1ZqzCNEEIFupDVYnbIaHmrgUxjMVzPhoIFenh0kaoiQz8=
